language: java
jdk:
- oraclejdk8
sudo: required
env:
  global:
  - secure: Hg3FOFJt7chuhy9T5tJ5lQt+N1YR0TEk+MZfD728a9px3FCgXY1d3/8n7GJYD7rz9d8f3DPVoSJO8aLmrxoKaprbCs7Cb1aHV36JO1kmvVS+h0WaLI5nVXHVfgGyZt42sBkkXqm7lhOZ+Whkh7jaTipZzEunPgvlY44tk6SJcwmQdYGa8k6NE5rjnL3+wThDzAtPRIDVq8FBQCcxCRW4HQW0kE+dxR9F7qNMCU906dYagNuNK7B+VRmvULHKTYznlj+qy6oWRge4wlnkKTbR/pkM9iJ6RGg2IJ6xca7X+T7JXY0gOBLm2jhzzBDkg78t2pLxeMbo2HsOdOzHtt/+279UGBIFYSkZNl/N4LLin9z/OAf9BP6FIM8QcejR+h1NNu98cx3/d8w3NojO0tbED9dFCpGOjv9H+X6RfFPjUWVu59oS9RNBvNFqKvmNmvHJ/Kxrs1hYLOBUdjqDKPlkPpEtgCkm56n5CO4JPcz0pt8iyYQuLmVqdVwBN1nzMO3hgtaUDZtp5eYcK6xyI5tXv9X0kpLqUC6W7kqSgIbaTjs5h1xroUqcGu1I4H2OWYbStPDhl/LiSlk9IEYsi9GA+fUo/HmZDBZ7j2oAovUFRcDXqUqVMQapqCSQpviSLeZJKN/T0vD2U87rMAQWHAsZbBabpAakdFGorghPLTBXL78=
  - secure: WrDJ9hGz2jZSvs98z4vM0Z1LMApv3XhpWCHUDKena0yUc36ORUdilcVE4hjTmDvaoWEHzeU3xsXtSf8kECl0JbX50LNYa402cQWgo+NC2W0lIZ2CJxAmuz8eECChkz7hZtCVl45Tu2KHpxeN97ojjsNMnWT7AcJWfwjf+bBGxERB/q3a91Umvk+LbujFNDD+zN7IORxdNbkPNDDg0BD/ei0Kvw6OIQ4vQp3Yd3wxOB4znXhOIueHHQb23cTrMKTRNldzFoeJaSTX6fXK44Eo3GLCUEa95w7OeSN0RYsVWfgXAB3oI/bFYqQlEkg15/MA0QkishIxC6vhkkzjBYvPNgqoC8fbE7ZRUwDbeHGENjLWuAO8rkM/k99wDA/ygpAafN0TqO6o6YNP3nwyJKfYvaBHnKmyoCP/cdmOi+iGPVKnVa0oLSV0YDDooEMv/tzEFBe490gHnrw8ZJPMDnAH4FqyTwCFpQqhqLEwWurk/kl6pcGcY+jLx62eF4oIvw1HDqSaWUPN8SvnZQzvGqNkInY72DHOAQ3qkBAS3bV0BgUClIfvtiabxchDwRI6V9TZkhN+iEyCSY+++1zZ19reDmZZ60xLtHyEqmHQbIQ+Ign9mOKFn3Mnu9SDy0rvxme6m0L1UZ5PsfzQj6LqxTUhWV8INJda0U++j+7hXRDnlgc=
script: gradle runAllTestsInFirefox -PuserName=[USER_NAME] -Pkey=[KEY]
branches: 
only: master
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
