language: java
jdk:
- oraclejdk8
sudo: required
script: gradle runAllTestsInFirefox -PuserName=lourdesvillca1 -Pkey=KEY
branches: 
only: master
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
env:
  global:
    - KEY=secure: kXwhEIF15slepAvTWsELrCKy96ojPNt6vLgc/xPYthzuPHqxQbG2ykPi/bA9pbJP32JcJ2OfhTSeNB0ZQc+Y+FXPeV+wLV5+LGfXhn3g43MsqkOY9BXrtHa8P1pMmb9NSqXlo3x8LGl4niuiUyZrqEpZwJEpnS0U9Zc287a509anQ7zjkz2TCA7kXp3ratHe72EugmmzwyuWFKGmGzOcNXp1p4nCk8uIythVLInGlmxo8tJjXYMhty0ienMkPUzGhvQtnz0FRdgFAplFJvQtApOR11gIWqxL6BH5ahPN5tTcZjV8KtgZsxBN9vVGR7dhVWZtp0PvsnMI4yhg93xt6Gcs7kG8oppovkRRV/Lhe6IkLFbNGrSnzKkP33viCEmL6ltR1aY2/ExdXzCeqdccac3F10N3RhcIYovjvxSlN2JHd3NWIracsa519EqT3STt2wJakUWbPRUhtD/XvpQFxEF6NfsSMCmPh+a5tnNS+VgVR0lnNlR7S0axL+nFwrEnlknTTK7feRrUZpyyazqsEAJTHEgcUL7Boe8tR2IE1whacy1Y1KN3iep7QU/g+1tfBzEafNPIRjaLW+ttBU03W0nYiGbjs4Dx3FJIXLA/rs6iMwsSIbVcDv0gsD2E3HPKJnGPgK37skeLvijc4QXvKy5Oc1Rp3FvCMo4zJ/DSyIc=
